
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ExportButtonProps {
  data: {
    finalAmount: number;
    totalContributions: number;
    interestEarned: number;
    weaknessItemCount: number;
    weaknessType: string;
  };
}

export function ExportButton({ data }: ExportButtonProps) {
  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      maximumFractionDigits: 0,
    }).format(value);
  };

  const handleExport = () => {
    const content = `Investment Summary Report

Final Amount: ${formatCurrency(data.finalAmount)}
Total Contributions: ${formatCurrency(data.totalContributions)}
Interest Earned: ${formatCurrency(data.interestEarned)}
Items Not Purchased: ${data.weaknessItemCount.toLocaleString()} ${data.weaknessType}

Generated by Habit ROI Calculator
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'investment-summary.txt';
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <Button
      variant="outline"
      size="sm"
      className="flex items-center gap-2"
      onClick={handleExport}
    >
      <Download className="h-4 w-4" />
      Export Summary
    </Button>
  );
}
